### PR TITLE
Image from text

### PR DESCRIPTION
**Pull request by jbrennan**
This patch lets you create an `Image` by rendering a given string (with optional `font` and `textColor` parameters) into a buffer.

This is useful if you need to make an image from text (in particular, emoji) for things like particles, or if you need a text layer and you want to add touch handling to it, but you can’t because of #41 

This should be looked at after Swift 2 changes are merged in (#108)

### CODE REVIEW

**Comment by andymatuschak** [comment]
Whoa, some rough Git stuff happened here. I think 68a4206 is the only relevant revision?

**Comment by jbrennan** [comment]
> Whoa, some rough Git stuff happened here. I think 68a4206 is the only relevant revision?

Yeah, I think it’s because I was branching off of a branch off a branch, etc. As far as git is concerned, none of these commits were on master. I’ll try fixing this up (I imagine the Swift 2 PR suffers the same problems).

**Comment by jbrennan** [comment]
> Thought: for the same reason it's useful to be able to get an image of text, it's useful to be able to get an image of anything a layer can draw (e.g. a bezier path, etc). What if you could get an image (i.e. a snapshot) from any layer?

Yeah, that’d be lovely. I’ll make an issue for that.

> Even if you could do that, you'd probably still want a convenience API that looks like this, so I'm cool with rolling with this too.

Sweet!

> Mind bridging this to JS? I don't want the API surface to get skewed.

Ah yes, I will do that.

**Comment by jbrennan** [comment]
Ugh, more git messiness (I need a better strategy for keeping my fork in sync with Khan/Prototope). The relevant commit for the JS bridge is 1a080394 @andymatuschak

**Comment by andymatuschak** [comment]
Sweet, thanks. :)

**Pull request merged**
