### PR TITLE
Swift 2

### PR DESCRIPTION
**Pull request by jbrennan**
Upgrades Prototope to Swift 2.

(This should be looked at after #105 is merged in)

### CODE REVIEW

**Comment by andymatuschak** [comment]
Yay! These are all definitely changes for the better. Will merge after #105 is landed.

**Comment by jbrennan** [comment]
@andymatuschak bump :)

**Comment by andymatuschak** [comment]
Beep boop bop bope!

**Comment by jbrennan** [comment]
*/me triumphantly boops*

**Pull request merged**
