### PR TITLE
Bridge the Point.slopeToPoint() function.

### LINKED ISSUE #66: Bridge Point.slope method

### PR DESCRIPTION
**Pull request by jbrennan**
Is it possible (or does it make sense) to bridge an optional type?

The slope function is optional for the case where the slope is infinite/undefined (i.e., there's a divide by zero). For the bridge I'm just returning 0 because it seems more sensible to do this than really worry about it too much. Thoughts?

[Fixes #66]

### CODE REVIEW

**Comment by andymatuschak** [comment]
Nil is bridged to undefined, which seems appropriate in this context.

**Comment by jbrennan** [comment]
Do you think that'd be practical for prototyping purposes? (I suppose this applies equally well to the Swift version as it does the bridge :))

**Comment by andymatuschak** [comment]
Yeah, sounds very reasonable to me.

**Comment by jbrennan** [comment]
> Yeah, sounds very reasonable to me.

Er, practical for it to be nil or practical for it to be 0?

**Comment by andymatuschak** [comment]
Nil! 0 is out and out wrong.

**Comment by jbrennan** [comment]
@andymatuschak Should be gtg

**Comment by andymatuschak** [comment]
:+1:

**Pull request merged**
